baseURL = 'https://lchollet.github.io/lchollet/'
languageCode = 'ch-fr'
title = 'Portfolio'
theme = 'hugo-blog-awesome'

[menus]
[[menus.main]]
    identifier = 'about'
    name = 'À propos'
    pageRef = '/about'
    weight = 10
[[menus.main]]
    identifier = 'linkedin'
    name = 'Linkedin'
    url = 'https://www.linkedin.com/in/l%C3%A9o-chollet-0354a8241/'
    weight = 20